// lib/models/dose_log.dart

class DoseLog {
  final String id;
  final String scheduleId;
  final String medicationId;
  final String patientId;
  final DateTime scheduledFor;
  final DateTime? loggedAt;
  final String status;
  final int? deviationMinutes;
  final String? prnReason;
  final String? confirmedBy;
  final String? notes;
  final DateTime createdAt;

  DoseLog({
    required this.id,
    required this.scheduleId,
    required this.medicationId,
    required this.patientId,
    required this.scheduledFor,
    this.loggedAt,
    required this.status,
    this.deviationMinutes,
    this.prnReason,
    this.confirmedBy,
    this.notes,
    required this.createdAt,
  });

  factory DoseLog.fromJson(Map<String, dynamic> json) {
    return DoseLog(
      id: json['id'] as String,
      scheduleId: json['schedule_id'] as String,
      medicationId: json['medication_id'] as String,
      patientId: json['patient_id'] as String,
      scheduledFor: DateTime.parse(json['scheduled_for'] as String),
      loggedAt: json['logged_at'] != null
          ? DateTime.parse(json['logged_at'] as String)
          : null,
      status: json['status'] as String,
      deviationMinutes: json['deviation_minutes'] as int?,
      prnReason: json['prn_reason'] as String?,
      confirmedBy: json['confirmed_by'] as String?,
      notes: json['notes'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  /// Only for creating new dose logs
  /// deviation_minutes is computed by the database
  /// created_at is handled by Supabase
  Map<String, dynamic> toJson() {
    return {
      'schedule_id': scheduleId,
      'medication_id': medicationId,
      'patient_id': patientId,
      'scheduled_for': scheduledFor.toIso8601String(),
      'logged_at': loggedAt?.toIso8601String(),
      'status': status,
      'prn_reason': prnReason,
      'confirmed_by': confirmedBy,
      'notes': notes,
    };
    // deviation_minutes is GENERATED by database
    // created_at is DEFAULT NOW() in database
  }

  /// Status helpers
  bool get isPending => status == 'pending';
  bool get isTaken => status == 'taken';
  bool get isLate => status == 'late';
  bool get isSkipped => status == 'skipped';
  bool get isMissed => status == 'missed';

  bool get wasCompleted => isTaken || isLate;
  bool get wasNotTaken => isSkipped || isMissed;

  /// Was this dose taken early?
  bool get wasTakenEarly =>
      deviationMinutes != null && deviationMinutes! < 0;

  /// Was this dose taken late?
  bool get wasTakenLate =>
      deviationMinutes != null && deviationMinutes! > 0;
}